/**
 * Offline storage for Minotor RAPTOR routing data: patterns.json (weekday
 * service-pattern manifest, see pipeline/generate_transit_data.mjs), one
 * timetable.<hash>.bin per distinct pattern it references (usually 1, up to
 * 7), and the single shared stops.bin - plus freshness checking against the
 * server's version.json. Module singleton (all callers share state), same
 * reasoning as useOfflineTiles.ts, which owns the tile-download half of
 * offline storage and re-exports this module's public API.
 */

import { reactive } from 'vue'
import { idbGet, idbPut, idbDelete, idbKeys } from '@/services/offlineDb'
import type { PatternsManifest } from '@/types'

const WEEKDAY_KEYS = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'] as const

export function weekdayKeyForDate(dateStr?: string | null): typeof WEEKDAY_KEYS[number] {
  // Parsed/read as UTC throughout (pipeline, server, and here) so the same
  // "YYYY-MM-DD" always resolves to the same weekday regardless of the
  // device's local timezone.
  const d = dateStr ? new Date(`${dateStr}T00:00:00Z`) : new Date()
  return WEEKDAY_KEYS[d.getUTCDay()]
}

export const downloadedAt  = reactive<Record<string, string>>({})   // slug → ISO string (when routing data was last downloaded)
export const updateAvail   = reactive<Record<string, boolean>>({})  // slug → true when server has newer routing data
export const updatingData  = reactive<Record<string, boolean>>({})  // slug → true while an updateDataFiles() call is in flight

// Silently checks whether the server has newer routing data for a city.
// Sets updateAvail[slug] if version.json is newer than the stored downloadedAt.
export async function checkForUpdates(slug: string): Promise<void> {
  try {
    const resp = await fetch(`/data/${slug}/version.json`, { cache: 'no-store' })
    if (!resp.ok) return
    const { generatedAt } = await resp.json() as { generatedAt: string }
    const localTs = downloadedAt[slug]
    updateAvail[slug] = !localTs || new Date(generatedAt) > new Date(localTs)
  } catch { /* offline or no version.json yet — leave updateAvail unchanged */ }
}

// Fetches and stores the Minotor RAPTOR binaries for offline routing -
// patterns.json plus one timetable.<hash>.bin per distinct weekday pattern
// it references (usually 1, up to 7), and the single shared stops.bin -
// stamping downloadedAt in lockstep (offlineRouter.ts's cache key depends on
// that pairing). Generated by the pipeline (see
// pipeline/generate_transit_data.mjs). Shared by the initial city download
// and the lighter data-only update. Throws on HTTP failure - callers decide
// whether that's fatal (updateDataFiles) or non-critical (downloadCity).
export async function storeRoutingData(slug: string): Promise<void> {
  const patternsResp = await fetch(`/data/${slug}/patterns.json`)
  if (!patternsResp.ok) throw new Error(`HTTP error fetching routing data`)
  const patterns = await patternsResp.json() as PatternsManifest
  const hashes = [...new Set(Object.values(patterns.weekdayToPattern))]

  const [stResp, ...ttResps] = await Promise.all([
    fetch(`/data/${slug}/stops.bin`),
    ...hashes.map(hash => fetch(`/data/${slug}/timetable.${hash}.bin`)),
  ])
  if (!stResp.ok || ttResps.some(r => !r.ok)) throw new Error(`HTTP error fetching routing data`)
  const [stBuf, ...ttBufs] = await Promise.all([stResp.arrayBuffer(), ...ttResps.map(r => r.arrayBuffer())])

  // Drop pattern binaries from a previous generation that are no longer
  // referenced (e.g. the GTFS calendar shifted and a weekday now maps to a
  // different hash) so IndexedDB doesn't accumulate stale binaries forever.
  const keepKeys = new Set(hashes.map(hash => `timetable-${slug}-${hash}`))
  const staleKeys = (await idbKeys()).filter(k => k.startsWith(`timetable-${slug}-`) && !keepKeys.has(k))
  await Promise.all(staleKeys.map(idbDelete))

  const now = new Date().toISOString()
  await Promise.all([
    idbPut(`patterns-${slug}`, patterns),
    idbPut(`stops-${slug}`, stBuf),
    ...hashes.map((hash, i) => idbPut(`timetable-${slug}-${hash}`, ttBufs[i])),
    idbPut(`downloadedAt-${slug}`, now),
  ])
  downloadedAt[slug] = now
  updateAvail[slug] = false
}

// Re-downloads only the routing data files (patterns.json + timetable.<hash>.bin + stops.bin + routes.json).
// Much faster than a full tile re-download; tiles almost never change.
export async function updateDataFiles(slug: string): Promise<void> {
  updatingData[slug] = true
  try {
    await storeRoutingData(slug)
    try {
      const cache = await caches.open('city-routes')
      await Promise.all([
        cache.delete(`/data/${slug}/routes.json`),
        cache.delete(`/data/${slug}/routes-meta.json`),
      ])
      await Promise.all([
        cache.add(`/data/${slug}/routes.json`),
        cache.add(`/data/${slug}/routes-meta.json`),
      ])
    } catch { /* non-critical */ }
  } finally {
    delete updatingData[slug]
  }
}

/**
 * Returns the Minotor RAPTOR binary data for a city on the given date (or
 * today, if omitted), or null if not stored locally. Also null when the
 * date falls on a known calendar_dates.txt exception - the weekday
 * patterns stored offline don't model those, so callers should fall back
 * to an online request instead of silently showing the wrong schedule.
 */
export async function getMinotorData(
  slug: string,
  date?: string | null,
): Promise<{ timetableData: Uint8Array; stopsData: Uint8Array; patternHash: string } | null> {
  try {
    const patterns = await idbGet<PatternsManifest>(`patterns-${slug}`)
    if (!patterns) return null
    if (date && patterns.exceptionDates.includes(date)) return null

    const hash = patterns.weekdayToPattern[weekdayKeyForDate(date)]
    const [ttBuf, stBuf] = await Promise.all([
      idbGet<ArrayBuffer>(`timetable-${slug}-${hash}`),
      idbGet<ArrayBuffer>(`stops-${slug}`),
    ])
    if (!ttBuf || !stBuf) return null
    return { timetableData: new Uint8Array(ttBuf), stopsData: new Uint8Array(stBuf), patternHash: hash }
  } catch { return null }
}

/** Removes all stored routing data for a city (patterns manifest, every timetable binary, stops, and freshness state). */
export async function deleteRoutingData(slug: string): Promise<void> {
  const patternKeys = (await idbKeys()).filter(k => k.startsWith(`timetable-${slug}-`))
  await Promise.all([
    idbDelete(`patterns-${slug}`),
    idbDelete(`stops-${slug}`),
    idbDelete(`downloadedAt-${slug}`),
    ...patternKeys.map(idbDelete),
  ])
  delete downloadedAt[slug]
  delete updateAvail[slug]
}
